#!/bin/sh

# Program to initialize an SSH configuration with a host. Makes a new SSH key, 
# copies that to the host, appends the use of that key to the local 
# ~/.ssh/config. If the -r option is invoked, it will also su into the host's
# root user, and copy the ssh key there.

# Usage: 
#   ssh-init [-r] user@host


# Parse arguments.
usage='ssh-init [-r] user@host'
root=0
for arg in "$@"; do
    echo "$arg"
    case $1 in
        -r) 
            root=1
            ;;
        *@*) 
            target=$arg
            echo target: $target
            ;;
        *)
            echo $usage
            ;;
    esac
done

username=$(echo $target |cut -d \@ -f 1)
hostname=$(echo $target |cut -d \@ -f 2)
keypath=$HOME/.ssh/auto/$target
pubpath=$keypath.pub
config=$HOME/.ssh/config

# Makes a keypair with no password, and an unidentifying comment.
makeKey () {
    mkdir -p $HOME/.ssh/auto
    chmod 700 $HOME/.ssh/auto
    ssh-keygen -t ed25519 -f $HOME/.ssh/auto/$target -C $target -N ""
    echo "Keypair created in $HOME/.ssh/auto"
}
# Adds configuration in ~/.ssh/config which will invoke the keypair and 
# user. 
appendConfig () {
    echo "" >> $config
    echo "Host $hostname" >> $config

    if [ $root -eq 1 ]; then
        echo "    user root" >> $config
    else
        echo "    user $username" >> $config
    fi
    echo "    IdentityFile $keypath" >> $config
    echo "Configuration added to $config"
}
insertId () {
    ssh-copy-id -i $pubpath $target
    appendConfig
    if [ $root -eq 1 ]; then
        ssh $target 'su -c "mkdir -p /root/.ssh; tail -n 1 >> /root/.ssh/authorized_keys"'
    fi
    echo "Key installed on remote machine."
}

echo $target

appendConfig
makeKey
insertId
